config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tweets#index'
  # resources :tweets, only: [:index, :new, :create, :destroy, :edit, :update, :show] => リファクタリング後
  resources :tweets do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
end

# tweets/newでtweetsコントローラーのnewアクションへ振り分ける。

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
  has_many :comments

  def self.search(search) # 投稿を表示するメソッド

    if search
      Tweet.where( "text LIKE(?)", "#{search}" )
    else
      Tweet.all
    end

  end

end

# コントローラークラスでクラスメソッドであるcreateメソッドがTweetモデルに対して使えるのは
# 恐らくApplicationRecordクラスが所有しているcreateメソッド(クラスメソッド)にDBをいじるSQLとのロジックが組まれている。
# Tweetモデルはそのクラスを継承している。

# バリデーションはモデルクラスに記載。
# このバリデーションの設定で空のツイートは登録不可能になった。

# コントローラーはあくまでモデルの機能を利用し処理を呼ぶだけで、複雑な処理は組まない。

# where => モデル.where(条件)のように引数部分に条件を指定することで、テーブル内の条件に一致したレコードのインスタンスを配列の形で取得できます。

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permmited_parameters, if: :devise_controller?

  private

  def configure_permmited_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:nickname])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    comment = Comment.create(comment_params)
    redirect_to "/tweets/#{comment.tweet.id}"
  end

  private

    def comment_params
      params.require(:comment).permit(:text).merge(user_id: current_user.id , tweet_id: params[:tweet_id] )
    end

end


# 10行目 => user_idとtweet_idに何を保存したいかを考える。user_idは現在ログインしているユーザー, tweet_idはその投稿のid
# もし難しかったら、先にコメントのフォームを実装して、ストロングパラメーター内で最初にbinding.pryを実装する。そうすればどのようにDBに保存するかが分かる。

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  # before_action :set_tweets, only: [:edit, :show] 今回は実装なし

  before_action :move_to_index, except: [:index, :show, :search]
  # == new,create,edit,update,destoryは全てindex.html.erbにリダイレクトされる。

  def index
    @tweets = Tweet.includes(:user).order("created_at DESC").page(params[:page]).per(5)
  end

  def new
    @tweet = Tweet.new
    # => 新規投稿ページのビューへ。
  end
  
  def create
    Tweet.create(tweets_params)
    # => 投稿完了のビューへ。
  end

  def edit
    @tweet = Tweet.find(params[:id])
    # => ビューで使う為インスタンス変数が必要 編集画面のビューへ。
  end

  def update
    tweet = Tweet.find(params[:id])
    tweet.update(tweets_params)
    # => 編集完了のビューへ。
  end

  # ここでのfind(params[:id])はedit.html.erbのパラメーター
  # データをDBに保存する為、privateメソッドでストロングパラメーターを設定する

  def show
    
    @tweet = Tweet.find(params[:id]) # => 各詳細ページのビューへ。
    @comment = Comment.new # form_withで使用する為のインスタンス。
    @comments = @tweet.comments.includes(:user) # アソシエーションの正しいデータの取得。ビューのコメント一覧でuser情報を表示するため、ここでuserモデルを一緒に取得。あくまで全て指定はモデル。

  end

  # ここでのfind(params[:id])はindex.html.erbで作成したlink_toのパラメーター

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    # => 削除完了のビューへ。
  end

  def search
    @tweets = Tweet.search(params[:keyword])
    # ここのパラメーターはform_withで設定した:keywordというキー。
  end

  private
  # 他のクラスからアクセス出来ないようにする。

  def tweets_params
    params.require(:tweet).permit(:text,:image).merge(user_id: current_user.id)
  end

  # def set_tweets
  #   @tweet = Tweet.find(params[:id])
  # end
  # # 今回は実装しないけど、記述が同じものに関しては、before_actionでまとめる。

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  # redirect_toは同一コントローラーの指定したアクションにリダイレクト可。

  # このように書くと先にuser_signed_in?で判定をして、その返り値がfalseだった場合に手前の式を実行する。ユーザーがログインしていない時にはindexアクションを実行するロジック。

end

# form_withでモデルクラスのインスタンスが必要な為、Tweetモデルのインスタンスをここで生成。

# createアクションはフォームで送られてきた情報を元にレコードを保存。ストロングパラメーターも忘れずに設定。 

# ビューで使う必要のないものはローカル変数を使用でOK

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show

    user = User.find(params[:id])
    @nickname = user.nickname
    @tweets = user.tweets.order("created_at DESC").page(params[:page]).per(3)

  end
end


## ビューで必要なものをまずは考える。=> ニックネームとtweets情報。色々な書き方があるけど上記でもOK。

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<%# アプリケーションのビューファイルの共通部分をまとめたもの == レイアウトテンプレート %>

<!DOCTYPE html>
<html>
  <head>
    <title>Pictweet</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script type="text/javascript">
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>
  </head>

  <body>

    <%# ヘッダーの固定 %>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">PicTweet</a></h1>

        <%# ユーザーがログインしていたら %>

        <% if user_signed_in? %>
        <div class="user_nav grid-6">
          <span><%= current_user.nickname %>
            <ul class="user__info">
              <li>
                <%= link_to "マイページ", "/users/#{current_user.id}" %>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </span>
          <%= link_to  "投稿する", "/tweets/new", class: "post" %>
        </div>
      
        <%# ユーザーがログアウト状態だったら %>

        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
      </div>
    </header>

    <%# yieldメソッドを使用し、全ての他のビューファイルを集約 %>
    <%= yield %>

    <%# フッターの固定 %>
    <footer>
      <p>
        Copyright PicTweet 2020.
      </p>
    </footer>
  
  </body>
    
  <%# current_user == 現在のログインしているユーザー == 自分のマイページ %>

app/views/tweets/_form.html.erb
<%= form.text_field :image, placeholder: "Image Url" %>
<%= form.text_area :text, placeholder: "text" , rows: "10" %>
<%= form.submit "SEND" %>

app/views/tweets/_tweet.html.erb
<div class="content_post" style="background-image: url(<%= tweet.image %>);">
  <div class="more">
    <span><i class="fas fa-arrow-down"></i></span>
    <ul class="more_list">
      <li>
        <%= link_to '詳細', "/tweets/#{tweet.id}", method: :get %>
      </li>
      <% if user_signed_in? && current_user.id == tweet.user_id %>
        <li>
          <%= link_to '編集', "/tweets/#{tweet.id}/edit", method: :get %>
        </li>
        <li>
          <%= link_to '削除', "/tweets/#{tweet.id}", method: :delete %>
        </li>
      <% end %>
    </ul>
  </div>
  <%= simple_format(tweet.text) %>
  <span class="name">
    <a href="/users/<%= tweet.user.id %>">
      <span>投稿者</span><%= tweet.user.nickname %>
    </a>
  </span>
</div>

<%# 部分テンプレートファイル %>

app/views/tweets/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      投稿が完了しました。
    </h3>
    <a class="btn" href="/tweets">投稿一覧へ戻る</a>
  </div>
</div>

app/views/tweets/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      削除が完了しました。
    </h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/tweets/edit.html.erb
<div class="contents row">
  <div class="container">
    <%= form_with(model: @tweet, local: true) do |form| %>
      <h3>
        編集する
      </h3>
    <%= render partial: "form", locals: { form: form } %>
    <% end %>
  </div>
</div>


<%# form_withの中では、formという変数を利用しているので、locals: { form: form }という記述になっていることに注意 eachメソッドのformを部分テンプレート先のformで使用する為、ここで変数化 %>

app/views/tweets/index.html.erb
<%= form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>

<%# 投稿を検索するform_with。データを保存しないためモデルクラスのインスタンス設定は行わない。 %>

<div class="contents row">
  <% @tweets.each do |tweet| %>
    <%= render partial: "tweet", locals: { tweet: tweet } %>
  <% end %>
  <%= paginate(@tweets) %>
</div>

<%# 8行目 tweet.idとできるのはtweetコントローラーにて記載してindexアクションのallメソッドで取得した@tweetsをeachメソッドで1つずつ処理している為tweet.idでそのhtmlで構成した画像が取得出来る %>
<%# ここでコントローラーのfind(params[:id]として取得するところで個々の削除したいidを取得する) %>
<%# link_toで行き先を指定するとき、ルーティングを設定してから、そこのコントローラーで動かしたいパスを明らかにするために、""" rails routes """で行き先を確認する。 %>

<%# ここでもコントローラーで全件ツイートを取得し、そこからuserテーブルを見に行っている == N+1問題 == 先にallではなくincludes(:user)でuserテーブルも関連づけて取得する。 %>

  <%# 10行目 %>
  <%# ログイン中ユーザーのid == 投稿したユーザーのidが一致すれば、編集・削除ボタンの表示を許可 %>

app/views/tweets/new.html.erb
<div class="contents row">
  <div class="container">
    <%= form_with(model: @tweet, local: true) do |form| %>
      <h3>
        投稿する
      </h3>
    <%= render partial: "form", locals: { form: form } %>
    <% end %>
  </div>
</div>


<%# form_withの中では、formという変数を利用しているので、locals: { form: form }という記述になっていることに注意 eachメソッドのformを部分テンプレート先のformで使用する為、ここで変数化 %>

app/views/tweets/search.html.erb
<%= form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @tweets.each do |tweet| %>
    <%= render partial: "tweet", locals: { tweet: tweet } %>
  <% end %>
</div>

<%# searchアクションに対するビュー %>

app/views/tweets/show.html.erb
<div class ="contents row">
  <div class="content_post" style="background-image: url(<%= @tweet.image %>);">
    <% if user_signed_in? && current_user.id == @tweet.user_id %>
      <div class="more">
        <span><i class="fas fa-arrow-down"></i></span>
        <ul class="more_list">
          <li>
            <%= link_to '編集', "/tweets/#{@tweet.id}/edit", method: :get %>
          </li>
          <li>
            <%= link_to '削除', "/tweets/#{@tweet.id}", method: :delete %>
          </li>
        </ul>
      </div>
    <% end %>
    <%= simple_format(@tweet.text) %>
    <span class="name">
      <a href="/users/<%= @tweet.user.id %>">
        <span>投稿者</span><%= @tweet.user.nickname %>
      </a>
    </span>
  </div>
  <div class="container">
    <% if current_user %>
      <%= form_with(model: [@tweet, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "SEND" %>
      <% end %>
    <% else %>
      <strong><p> ※※※ コメントの投稿には新規登録/ログインが必要です ※※※ </p></strong>
    <% end %>

    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
            <%= comment.text %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<%# tweets/index.html.erbと同じ構造。ただ詳細表示する投稿は1つなので、each文はなし。%>

<%# ログインしていたらコメント欄を出す。ログインしていなかったら注意書きを表示。 %>

app/views/tweets/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      更新が完了しました。
    </h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/users/show.html.erb
<div class="contents row">
  <p><%= @nickname %>さんの投稿一覧</p>

  <% @tweets.each do |tweet| %>
    <%= render partial: "tweets/tweet", locals: { tweet: tweet } %>
  <% end %>
  <%= paginate(@tweets) %>
</div>